# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np    # numpy를 import해서 np로 줄임말로 사용

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)   # __version__ 매직메서드로 버전 출력
np.show_config()    # NumPy가 빌드된 시스템의 라이브러리를 표시합니다.

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
Z = np.zeros(10)    # Z에 0으로 채워진 지정된 모양과 유형의 새 배열을 반환합니다.
print(Z)    # Z를 출력합니다.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
Z = np.zeros((10,10))   # Z에 0으로 채워진 지정된 모양과 유형의 새 배열을 반환합니다.
print("%d bytes" % (Z.size * Z.itemsize))   # 배열의 메모리 크기는 배열크기 * 항목크기 * 바이트 = (100 * 8 * byte)

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add) # add function에 대한 설명서

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
Z = np.zeros(10)    # Z에 0으로 채워진 지정된 모양과 유형의 새 배열을 반환합니다.
Z[4] = 1    # Z의 5번째에 1의 값을 넣는다.
print(Z)    # Z를 출력한다.

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
Z = np.arange(10,50)  # Z에 10부터 49까지를 배열로 지정한다.
print(Z)    # Z를 출력한다.

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
Z = np.arange(50)   # 크기가 50인 배열을 지정한다.
Z = Z[::-1]   # 배열을 인덱싱을 활용하여 뒤집는다.
print(Z)    # Z를 출력한다.

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
Z = np.arange(9).reshape(3, 3)    # 크기가 9인 배열을 만들고 reshape으로 재 지정해준다.
print(Z)  # Z를 출력한다.

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])    # nonzero로 0이 아닌 요소를 nz에 저장
print(nz)   # nz 출력

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
Z = np.eye(3)   # eye를 사용하여 3 * 3 배열을 만듦
print(Z)  # Z를 출력

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
Z = np.random.random((3,3,3))   # random으로 임의의 값을 가진 3 * 3 * 3배열 만듦
print(Z)    # Z 출력

[[[0.88489559 0.50477343 0.51930623]
  [0.89902717 0.15512392 0.12538662]
  [0.92063371 0.13230759 0.15224239]]

 [[0.83898199 0.40670313 0.14727724]
  [0.03305834 0.61595237 0.68746714]
  [0.98545958 0.57077375 0.34509915]]

 [[0.77224508 0.58380653 0.7913656 ]
  [0.04478372 0.20282519 0.5907839 ]
  [0.13265575 0.18278481 0.12720691]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
Z = np.random.random((10,10))   # random으로 임의의 값을 가진 3 * 3 * 3배열 만듦
Zmin, Zmax = Z.min(), Z.max()   # Zmin에는 최소값, Zmax에는 최대값을 저장
print(Zmin, Zmax)   # 최소 최대값 출력

0.0026870452568850123 0.9861335954181806


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
Z = np.random.random(30)    # random으로 임의의 값을 가진 3 * 3 * 3배열 만듦
m = Z.mean()    # mean으로 평균값 구함
print(m)    # m 출력

0.5552439472857401


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
Z = np.ones((10,10))  # 1로 가득찬 10 * 10 배열 생성
Z[1:-1,1:-1] = 0    # 인덱싱을 사용하여 테두리를 제외하고 0의 값을 저장
print(Z)    # Z 출력

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
Z = np.ones((5,5))    # 1로 가득찬 5 * 5 배열 생성
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)    # pad를 사용하여 테두리에 0을 패딩함
print(Z)  # Z를 출력

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)   # nan은 값이 유효한지 검사
print(np.nan == np.nan)   # nan은 자신과 비교하면 동일하지 않다고 나옴.
print(np.inf > np.nan)    # inf는 최대값이기에 nan을 사용하여 비교하면 false를 출력
print(np.nan - np.nan)    # nan에 nan을 빼면 nan이 출력됨
print(np.nan in set([np.nan]))    # 집합안에 넣어서 비교하면 np.nan == np.nan과 다르게 true가 출력됨
print(0.3 == 3 * 0.1)   # 부동소수점으로 인해 오차 발생

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Z = np.diag(1+np.arange(4),k=-1)  # 2차원이기에 diag 사용가능해서 diag로 대각선에 1234값 넣음
print(Z)    # Z 출력

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
Z = np.zeros((8,8),dtype=int)   # 배열 8 * 8에 0을 넣은 배열 선언 int형을 넣어 소수점 제거
Z[1::2,::2] = 1   # 홀수줄 바둑판 생성
Z[::2,1::2] = 1   # 짝수줄 바둑판 생성
print(Z)    # 출력

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
print(np.unravel_index(99,(6,7,8)))   # unravel_index는 평면 인덱스 배열을 좌표 배열 튜플로 변환합니다. 즉 100번째 요소의 인덱스 (6 ,7 ,8)은 앞의 명령어와 같음

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))    # tile함수를 이용 배열을 복붙함
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
Z = np.random.random((5,5))   # 랜덤한 값을 가진 5 * 5 배열 선언
Z = (Z - np.mean (Z)) / (np.std (Z))    # Z에 평균값을 빼고 표준편차를 나눠 정규화함
print(Z)

[[-0.74308811  1.23206437 -0.13935289  0.79515884  0.77160438]
 [ 1.27822141 -1.03012731 -0.28666524 -0.56331296 -1.70431227]
 [ 0.96762747 -1.16184349  0.13223257 -1.53215548 -1.32617941]
 [ 1.36198029 -0.74770708 -0.48774294  1.32363904  0.43375629]
 [-0.40660601  0.77321776  0.99519229  1.24171686 -1.17731839]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("r", np.ubyte),  # r ubyte
                  ("g", np.ubyte),  # g ubyte
                  ("b", np.ubyte),  # b ubyte
                  ("a", np.ubyte)]) # a ubyte

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))    # dot를 사용하여 5 * 3과 3 * 2 함수를 곱함
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
Z = np.arange(11)   # 0 ~ 11의 배열 생성
Z[(3 < Z) & (Z < 8)] *= -1    # 3과 8사이의 배열을 -1을 곱해줌
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))   # import 전이라서 (1 + 2 + 3 + 4 + -1)9가 출력
from numpy import *   # numpy.sum(a, axis=None, dtype=None, out=None, ...)
print(sum(range(5),-1))   # import 후라서 (1 + 2 + 3 + 4)10이 출력 axis = -1

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
print(Z**Z)    # Z의 제곱
print(2 << Z >> 2)   #  시프트 연산자
print(Z <- Z)  # Z < -Z인지 잘 모르겠으나 Z < -Z라고 가정하면 비교연산자임
print(1j*Z)    # 1j는 복소단위
print(Z/1/1)   # Z/1/1
# Z<Z>Z 에러 발생

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))  # 값이 유효한지 검사
print(np.array(0) // np.array(0)) # 몫을 확인
print(np.array([np.nan]).astype(int).astype(float))   #  NaN(float)을 포함하는 배열을 만든 다음 int로 캐스팅한 다음 다시 float로 캐스팅, NaN은 int로 표현할 수 없기 때문에 이상한 숫자를 얻는다.

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)   # 난수값 지정
print(np.copysign(np.ceil(np.abs(Z)), Z))   # ceil로 정수를 올림함, copysign으로 float형으로 반환

[-7. -2. -8. -6.  2.  1.  4.  9. -2.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
Z1 = np.random.randint(0,10,10)   # 랜덤한값의 배열 지정
Z2 = np.random.randint(0,10,10)   # 랜덤한값의 배열 지정
print(np.intersect1d(Z1,Z2))      # intersect1d로 교집합을 사용하여 같은값을 출력

[0 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
defaults = np.seterr(all="ignore")  # np.seterr 메서드 사용하여 all을 ignore로 설정해서 오류 발생시 아무것도 안함
Z = np.ones(1) / 0 
_ = np.seterr(**defaults)
# 원래 상태로 복귀
with np.errstate(all="ignore"):   # 경고를 표시하지 않도록 np.errstate를 사용
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)  # np.emath.sprt(-1)은 1j로 표시됨으로 값이 다름

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)  # datetime에 1의값을 빼 어제값 지정
today     = np.datetime64('today')    # datetime으로 오늘 날자 지정
tomorrow  = np.datetime64('today') + np.timedelta64(1)  # datetime에 1의값을 더하여 어제값 지정

print(yesterday)
print(today)
print(tomorrow)

2022-05-10
2022-05-11
2022-05-12


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')  # np.arange로 7월날자를 배열에 넣고 dtype으로 type을 str형으로 맞추어 오류를 제거
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))    # A + B의 값을 B에 저장
print(np.divide(A,2,out=A)) # A / B의 값을 A에 저장
print(np.negative(A,out=A)) # -(A / B)의 값을 A에 저장
print(np.multiply(A,B,out=A)) # (A + B) * (-A / 2)와 같은 결과
print(A)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)  # 배열을 1로 나눈 나머지를 빼서 정수부분 구하기
print(Z // 1)   # 배열을 1로 나눈 몫을 구하기
print(np.floor(Z))  # np.ceil을 이용해 올림
print(Z.astype(int))  # .astype(int)를 사용해 데이터타입을 integer로 변환
print(np.trunc(Z))  # trunc를 사용해 소숫자리를 자르고 value 표시

[7. 4. 8. 3. 4. 3. 7. 9. 9. 6.]
[7. 4. 8. 3. 4. 3. 7. 9. 9. 6.]
[7. 4. 8. 3. 4. 3. 7. 9. 9. 6.]
[7 4 8 3 4 3 7 9 9 6]
[7. 4. 8. 3. 4. 3. 7. 9. 9. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
Z = np.zeros((5,5)) # 5 * 5 행렬 만듦
Z += np.arange(5)   # 만든 행렬에 값 넣기
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():   # generate 함수 선언
    for x in range(10):   # 포문으로 10개의 정수를 들어갈수있게 함
        yield x   # yield를 사용하여 끝내기보다 대기 후 실행할수있게 함
Z = np.fromiter(generate(),dtype=float,count=-1)  # fromiter는 순환가능한 객체로 1차원 배열을 생성 (함수, 데이터 타입, 기본값)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
Z = np.linspace(0,1,11,endpoint=False)  # 0에서 1사이 값으로 크기가 10인 배열 생성, endpoint=False는 마지막 숫자를 지정한 값이 아닌 다른 숫자로 변환
print(Z[1:])  #인덱스 [1:]로 첫번째 벡터 제외하여 10개 원소 배열로 변환

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
Z = np.random.random(10)  # 크기 10인 랜덤값 배열 선언
Z.sort()    # sort로 오름차순 정렬
print(Z)

[0.07055403 0.07409879 0.1328693  0.21190796 0.48929025 0.4981362
 0.55919676 0.70543023 0.84863995 0.97587939]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
Z = np.arange(10) # 크기가 10인 배열 과 값 선언
np.add.reduce(Z)  #np.sum에 reduce가 들어있어 sum을 사용시 reduce를 호출하여 사용하기 때문에 작은 배열의 경우 reduce가 더 빠름

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
A = np.random.randint(0,2,5)  # 배열 선언
B = np.random.randint(0,2,5)  # 배열 선언

equal = np.allclose(A,B)  # allclose는 배열이 모양이 같다고 가정하고 요소별로 같으면 true를 반환(조금의 오차는 허용)
print(equal)

equal = np.array_equal(A,B) # array_equal은 배열의 모양과 요소가 같으면 true를 반환(오차 허용 없음)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)    # 배열 선언
Z.flags.writeable = False   # 쓸수 있는지 즉, False의 경우, Read-Only
Z[0] = 1  # Z의 0번째 배열 출력

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
Z = np.random.random((10,2))  # 10 * 2 의 배열 생성
X,Y = Z[:,0], Z[:,1]    # X에 0열, Y에 1열 할당
R = np.sqrt(X**2+Y**2)  # (X의 제곱 + Y의 제곱)제곱근
T = np.arctan2(Y,X)     # 아크탄젠트(Y, X)
print(R)
print(T)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
Z = np.random.random(10)  # 크기가 10인 배열 선언
Z[Z.argmax()] = 0   # argmax를 사용하여 배열의 최대값 찾아서 0을 저장
print(Z)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])    # 5 * 5 float형 배열 선언
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),  # np.meshgrid(1차원 배열 벡터, copy=True, False, sparse=False, True, indexing='xy', 'ij') np.linspance(구간 시작점, 구간 끝점, 구간 내 숫자 개수)
                             np.linspace(0,1,5))  # Meshgrid를 통해 사각형 영역을 구성하는 가로축의 점들과 세로축의 점을 나타내는 두 벡터를 인수로 받아서 이 사각형 영역을 이루는 조합을 출력한다.
print(Z)  # 결과는 그리드 포인트의 x 값만을 표시하는 행렬과 y 값만을 표시하는 행렬 두 개로 분리하여 출력한다.

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) # np.subtract(A,B) 는 A - B를 의미한다.
print(np.linalg.det(C)) # linalg는 linearAlgebra를 말한다. det는 행렬의 배열의 결정자를 계산한다.

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:   # dtype에 데이터값을 집어넣음
   print(np.iinfo(dtype).min)     # int의 최소값
   print(np.iinfo(dtype).max)     # int의 최대값
for dtype in [np.float32, np.float64]:    # dtype에 데이터값을 집어넣음
   print(np.finfo(dtype).min)    #float의 최소값
   print(np.finfo(dtype).max)    #float의 최대값
   print(np.finfo(dtype).eps)    #float의 표현 가능한 작은 값

# iinfo()는 int에 대한 정보를 / finfo()는 float에 대한 정보를 준다. Eps는 표현가능한 가장 작은 값을 돌려준다.

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=float("inf"))   # set_printoptions로 출력설정을할 수 있다. threshold에 inf를 사용하여 최대값을 지정해 모든 값이 출력되도록 설정했다.
Z = np.zeros((40,40))   # 40 * 40 배열 선언
print(Z)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
Z = np.arange(100)    # 배열 선언
v = np.random.uniform(0,100)  # 0 ~ 100 사이의 난수값 저장
print(v)  # 난수값 확인
index = (np.abs(Z-v)).argmin()  # abs(Z - v)를 해서 0에 가장 가까운 값이 가장 작은 값이다. argmin은 배열의 가장 작은값을 알려준다. 
print(Z[index])   # 가장 가까운 값 출력

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),    # 값이 0인 구조화된 배열을 선언
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import matplotlib.pyplot as plt
Z = np.random.random((10,2))    # 10 * 2 배열을 만든다.
X,Y = np.atleast_2d(Z[:,0], Z[:,1])   # X에 0번째 열, Y에 1번째 열을넣는다.
print(X)  # X 출력
print(Y)  # Y 출력
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) # .T는 전치행렬으로 바꿔주는 역활을 함
print(D)  # D 출력

# scipy를 사용시 더 빠름
import scipy
import scipy.spatial  # scipy를 호출
# 아래는 잘 모르겠습니다.
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

plt.scatter(X,Y)
plt.grid()

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32) # np.random.rand는 0 ~ 1사이의 균일정규분포 난수 astype을 사용하여 float32로 데이터 타입 변경
Y = Z.view(np.int32) # view를 사용하여 int32형으로 보이는것을 Y에 집어넣음
print(Z.view(np.int32)) # 
print(Y)
Y[:] = Z  # Y에 Z값 지정
print(Y)
print(Z.view(np.int32))
# astype(copy=False) 사용 (in place니까)
# float32형은 정수에 8bit 부호에 1bit 소수점에 23bit를 사용
# int32형은 정수에 32bit다 사용
# 때문에 view로 보는것과 실제 값이 들어가는것에는 오차가 발생해서 값이 바뀜

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO   # StringIO는 실제 파일인것처럼 읽고 쓰기 가능하게 해줌

# 가짜 파일
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')    # s에 파일처럼 값 저장
Z = np.genfromtxt(s, delimiter=",", dtype=np.int) # genfromtxt는 텍스트 파일을 array형식으로 변환해준다.
print(Z)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)   # 3 * 3배열에 9까지 순서대로 선언
for index, value in np.ndenumerate(Z):  # ndeunmerate는 배열 좌표와 값의 쌍을 생성하는 반복자를 반환합니다.
    print(index, value)   # 총 9번 반복된다.
for index in np.ndindex(Z.shape):   # ndindex는 배열을 인덱싱하는 N차원 반복자 개체이다.
    print(index, Z[index])  # 총 9번 반복된다.

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
# 정규분포 공식 = 1/(σ√2π) * exp(−((x−μ) * (x−μ) * (2σ) * (2σ)))
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(X)  # 행으로 정렬
print(Y)  # 열로 정렬
# linspance로 -1 ~ 1 사이의 값을 10개의 요소로 생성한 후, meshgrid로 x, y를 좌표로 받아 행렬로 반환한다.
D = np.sqrt(X*X+Y*Y)  # (X * X + Y * Y)를 오름차순 정렬한다.
sigma, mu = 1.0, 0.0  # 변수에 값 저장
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )  # exp는 함수의 값을 지수함수로 변환시켜준다.
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))   # n * n크기의 배열 선언
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
# random.choice는 원소를 랜덤하게 p개 뽑아준다.(replace=False는 원소 중복을 없애준다.) put을 사용해서 뽑은 값을 1로 바꿔준다.
print(Z)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [ ]:
X = np.random.rand(5, 10)
# 5 * 10 크기의 배열을 0 ~ 1 사이의 균일분포 표준정규분포 난수로 생성
Y = X - X.mean(axis=1, keepdims=True)
# mean을 사용하여 평균을 구한다. axis가 1이기 때문에 행끼리 계산하고, keepdims=true이기 때문에 2차원배열로 생성
Y = X - X.mean(axis=1).reshape(-1, 1)
# Y에 reshape을 사용하여 배열의 모양을 바꾼다. 행의 위치에 -1이 있으니 원래 배열의 길이와 남은 차원으로 부터 추정한다.
print(Y)

#### 59. How to sort an array by the nth column? (★★☆)

In [ ]:
Z = np.random.randint(0,10,(3,3))   # 0 ~ 10 사이의 랜덤한 int형 값을 3 * 3 배열에 채워넣는다.
print(Z)
print(Z[Z[:,1].argsort()])  # argsort()로 배열을 정렬한다. Z[Z[:,1]]은 Z[array([1번째 열])]과 같다.

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
Z = np.random.randint(0,3,(3,10)) # 0 ~ 3 사이의 랜덤한 int형 값을 3 * 10 배열에 채워넣는다.
print(Z)
print((~Z.any(axis=0)).any()) # axis가 0이니 열끼리 계산하여 열이 전부 NULL값(0)인 경우가 1개라도 있는경우 True를 반환 아닌경우 False를 반환

#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
Z = np.random.uniform(0,1,10) # random.uniform으로 0 ~ 1 사이의 실수를 10개 반환한다.
z = 0.5 # 값 지정
print(f"랜덤한 값들 = {Z[:]}")
m = Z.flat[np.abs(Z - z).argmin()]  # Z에서 지정된 값을 뺀 후 절대값을 씌워서 최소값을 찾아 m에 저장한다.
print(f"가장 가까운 값 = {m}")

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:
A = np.arange(3).reshape(3,1) # 2까지의 값을 3 * 1크기의 배열에 저장한다.
B = np.arange(3).reshape(1,3) # 2까지의 값을 1 * 3크기의 배열에 저장한다.
print(A, B)
it = np.nditer([A,B,None])  # nditer은 배열을 반복하는 효율적인 다차원 반복기 개체이다. 
for x,y,z in it:
    z[...] = x + y
# x, y, z에 it을 넣고 배열 z에 x + y를 더한값을 넣는다.
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)   # view를 통해 cls를 보여주고 asarray를 통해 복사한다.
        obj.name = name   # name을 저장
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return    # obj값이 Nome일 경우 return
        self.info = getattr(obj, 'name', "no name")   # self.info에 obj에 존재하는 속성을 저장한다.

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
Z = np.ones(10) # Z에 1의값을 넣은 1차원 배열 생성
I = np.random.randint(0,len(Z),20)  # 0 ~ 10 사이의 랜덤정수형을 20까지 생성
Z += np.bincount(I, minlength=len(Z)) # 0 ~ 10까지 숫자가 몇 개 있는지 Z배열에 더함.
print(I)
print(Z)

np.add.at(Z, I, 1)  # Z배열에 I idx 위치에 더함
print(Z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = [1,2,3,4,5,6] # 배열 생성
I = [1,3,9,3,4,1] # 배열 생성
F = np.bincount(I,X)  # F에 0 ~ 10까지 I, X배열의 숫자가 몇개 있는지 배열로 생성
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte) # 0 ~ 3사이의 랜덤한 값을 배열로 만들고 astype으로 데이터 형식을 바꿔준다.
colors = np.unique(I.reshape(-1, 3), axis=0)  # reshape으로 배열의 모양을 만들고 unique로 고유한 값을 찾는다.
n = len(colors) # n에 colors의 길이를 넣는다.
print(n)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# A에 0 ~ 10사이의 랜덤한 정수값을 4차원 배열에 넣는다.
sum = A.sum(axis=(-2,-1))
print(sum)
# sum에서 행과 열을 하나씩 삭제한 후 더한 값을 2차원 배a.열에 저장한다.
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)  # shape[:-2] = (3, 4) 따라서, A.reshpae[3,4,4]
# reshape을 이용해서 배열의 모양을 바꾸고 sum에 값을 저장한다.
print(sum)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
D = np.random.uniform(0,1,100)  # 0 ~ 1사이의 실수 중 난수값을 저장
S = np.random.randint(0,10,100) # 0 ~ 1사이의 실수 중 난수값을 저장
D_sums = np.bincount(S, weights=D)  # 0 ~ 10사이의 개수를 배열에 저장
print(D_sums)
D_counts = np.bincount(S) # 0 ~ 10사이의 개수를 배열에 저장
D_means = D_sums / D_counts
print(D_means)

import pandas as pd   # 데이터 처리를 위한 라이브러리
print(pd.Series(D).groupby(S).mean()) # mean을 통해 평균을 구하고 groupby는 같은 값을 하나로 묶어준다. Series로 1차원 배열과 같은 자료구조로 만들어준다.

#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
A = np.random.uniform(0,1,(5,5))  # 0 ~ 1사이의 랜덤한 실수 중 난수값을 지정
B = np.random.uniform(0,1,(5,5))  # 0 ~ 1사이의 랜덤한 실수 중 난수값을 지정
print(A)
print(B)

print(np.diag(np.dot(A, B)))  # 느림
# dot으로 다차원 내적을 수행하고 diag로 대각 행렬을 추출해준다.
np.sum(A * B.T, axis=1) # 빠름
# B.T로 전치작업을 수행 후 A를 곱하고 axis가 1이기 때문에 행끼리 계산한다.
print(np.sum(A * B.T, axis=1))
print(np.einsum("ij,ji->i", A, B))  # 제일빠름
# ji->i 는 행을 기준으로 합하라는 뜻임

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5]) # 배열 생성
nz = 3  # 변수 저장
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz)) # Z의 길이 + (Z의 길이 - 1) * 변수 만큼의 배열 생성
Z0[::nz+1] = Z  # 인덱싱을 사용하여 0부터 끝까지 인덱싱이 3씩 더해져서 Z배열의 값이 들어감
print(Z0)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
A = np.ones((5,5,3))  # 5 * 5 * 3크기의 배열 선언
B = 2*np.ones((5,5))  # 5 * 5크기의 배열에 2값 들어가게 선언
print(A * B[:,:,None])  # 임시적으로 B의 배열을 3차원으로 바꿔서 곱함

#### 72. How to swap two rows of an array? (★★★)

In [ ]:
A = np.arange(25).reshape(5,5)  # 5 * 5 크기의 배열을 25까지 값을 넣어 생성
A[[0,1]] = A[[1,0]] # 행 인덱스를 사용해서 행 교체
print(A)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
faces = np.random.randint(0,100,(10,3)) # 0 ~ 100 사이의 랜덤한 정수값을 10 * 3 배열에 집어넣음
F = np.roll(faces.repeat(2,axis=1),-1,axis=1) # repeat를 사용해서 -1이 나오기 전까지 반복하고, roll을 사용해서 -1만큼 축을 이동시킨다.
F = F.reshape(len(F)*3,2) # F의 길이 * 3, 2의 모양으로 배열을 바꾼다.
F = np.sort(F,axis=1) # 오름차순 정렬
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] ) # G에 view를 사용하여 데이터타입을 저장한다.
G = np.unique(G)  # 배열의 고유한 값을 정렬한것을 G에 저장한다.
print(G)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])  # bincount를 사용해서 빈도수를 저장
A = np.repeat(np.arange(len(C)), C) # C의 길이(7)까지의 값을 repeat를 사용해서 반복한다.
print(A)

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float) # cumsum으로 a의 누적합계를 ret에 저장
    ret[n:] = ret[n:] - ret[:-n]  # ret에 인덱싱을 사용하여 마지막값을 제외한 값을 전부 뺌
    return ret[n - 1:] / n  # 배열[n - 1]반환
Z = np.arange(20)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window) # shape = (10 - 3 + 1, 3)
    print(type(a[0])) # a[0]의 데이터 타입이 64bit이기 때문에 8byte란걸 알 수 있음
    strides = (a.strides[0], a.strides[0])  # 1차원 배열이기 때문에 strides = (8, 8)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)  # 8 * 3의 모양으로 배열을 만듦
Z = rolling(np.arange(10), 3)
print(Z)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [ ]:
Z = np.random.randint(0,2,100)  # 0 ~ 2사이의 랜덤한 정수형 값을 100개를 선언
print(Z)
print(np.logical_not(Z, out=Z))  # 0과 1을 가진 배열의 경우 logical_not을 통하여 반전이 가능하다.

Z = np.random.uniform(-1.0,1.0,100) # -1과 1사이의 실수형값을 100까지 선언
print(Z)
print(np.negative(Z, out=Z))  # negative를 이용하여 부호를 가진 배열을 반전시킬 수 있다.

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)  # 제곱한 뒤 행끼리 더함
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    # U = ((P0의 0번째 열 - p의 0번째 인덱스) * T의 0번째 열 + (P0의 1번째 열 - p의 1번째 인덱스) * T의 1번째 열) / L
    U = U.reshape(len(U),1) # U를10 * 1의 배열의 모양으로 변경
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))  # D를 제곱한 뒤 행끼리 더한값을 오름차순 정렬

P0 = np.random.uniform(-10,10,(10,2)) # -10 ~ 10사이의 랜덤한 실수형 값을 10 * 2 크기의 배열로 생성
P1 = np.random.uniform(-10,10,(10,2)) # -10 ~ 10사이의 랜덤한 실수형 값을 10 * 2 크기의 배열로 생성
p  = np.random.uniform(-10,10,( 1,2)) # -10 ~ 10사이의 랜덤한 실수형 값을 1 * 2 크기의 배열로 생성
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2)) # -10 ~ 10사이의 랜덤한 실수형 값을 10 * 2 크기의 배열로 생성
P1 = np.random.uniform(-10,10,(10,2)) # -10 ~ 10사이의 랜덤한 실수형 값을 10 * 2 크기의 배열로 생성
p = np.random.uniform(-10, 10, (10,2))  # -10 ~ 10사이의 랜덤한 실수형 값을 10 * 2 크기의 배열로 생성
print(np.array([distance(P0,P1,p_i) for p_i in p]))
# 전 문제에서 선언한 함수를 사용한 후 p_i에 p의 값을 넣어서 배열 선언

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10)) # 0 ~ 10사이의 랜덤한 실수형 값을 10 * 10 크기의 배열로 생성
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
# 5 * 5 배열에 1을 넣었으나 fill을 곱해서 0이 들어감
P  = np.array(list(position)).astype(int)
# 1차원 배열에 1, 1을 넣고 데이터타입을 int로 변경
Rs = np.array(list(R.shape)).astype(int)
# 1차원 배열에 5, 5을 넣고 데이터타입을 int로 변경
Zs = np.array(list(Z.shape)).astype(int)
# 1차원 배열에 10, 10을 넣고 데이터타입을 int로 변경

R_start = np.zeros((len(shape),)).astype(int)
# 크기가 2인 1차원 배열을 만들고 데이터타입을 int로 변경
R_stop  = np.array(list(shape)).astype(int)
# 크기가 2인 1차원 배열을 만들고 5, 5를 넣고 데이터타입을 int로 변경
Z_start = (P-Rs//2) # 1 - 5 // 2
Z_stop  = (P+Rs//2)+Rs%2  # (1 + 5 //2) + 5 % 2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
# (0 - (-1)) tolist를 이용해서 numpy배열을 목록으로 변환
Z_start = (np.maximum(Z_start,0)).tolist()
# (0) tolist를 이용해서 numpy배열을 목록으로 변환
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
# (1, 5 - 0) tolist를 이용해서 numpy배열을 목록으로 변환
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
# (4) tolist를 이용해서 numpy배열을 목록으로 변환

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
# start와 stop을 R_start와 R_stop를 넣고 zip을 사용해서 데이터를 서로 엮어준후 슬라이스한다.
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
# start와 stop을 Z_start와 Z_stop를 넣고 zip을 사용해서 데이터를 서로 엮어준후 슬라이스한다.
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32) # 1 ~ 14까지의 값을 uint32형으로 배열에 저장한다.
R = stride_tricks.as_strided(Z,(11,4),(4,4))  # Z의 값을 11 * 4모양의 배열에 저장한다.
print(R)

#### 82. Compute a matrix rank (★★★)

In [ ]:
Z = np.random.uniform(0,1,(10,10))  # 0 ~ 1사이의 랜덤한값을 10 * 10 배열에 저장
U, S, V = np.linalg.svd(Z) # linalg.svd는 특이값을 분해할 수 있다.
print(U.shape, S.shape, V.shape)
rank = np.sum(S > 1e-10)  # S > 1e - 10이 정수로 걸러주는듯? 함
print(np.sum(S))
print(rank)

#### 83. How to find the most frequent value in an array?

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z))
print(np.bincount(Z).argmax())  # bincount를 써서 0 ~ 9사이의 개수를 배열에 저장하고 해당 배열중 가장 큰 인덱스 값을 출력한다.

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)  # 1 + (Z의 0번째 행 - 3)
j = 1 + (Z.shape[1]-3)  # 1 + (Z의 1번째 행 - 3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
# Z 의 값을 i * j * n * n크기의 배열로 int64형으로 배열값 저장
print(C)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value) # 자식 클래스에서 부모 클래스인 Symetric의 내용을 사용
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    print(Z)
    print(np.diag(Z.diagonal()))
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric) 
# asarray를 이용해서 Z + Z.T(.T는 전치연산자) - diagonal를 사용해서 대각행렬 찾은 후 diag를 사용해서 대각행렬을 제외한 값들 초기화 한 후 Symetric를 view로 보여줌

S = symetric(np.random.randint(0,10,(5,5))) # 함수 symetric를 이용해서 S에 값 저장
S[2,3] = 42 # S에 값 선언
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))  # 배열 생성
V = np.ones((p,n,1))  # 배열 생성
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
# axes = 0 : 텐서 곱 axes = 1 : 텐서 내적 axes = 2 : (기본값) 텐서 이중 수축
# 쌍을 이루는 축 0, 0에대해 합산 이후 2, 1벡터 유지
print(S)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
Z = np.ones((16,16))  # 배열 선언
k = 4
print(Z.shape[0])
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
# 배열Z를 reduceeat를 사용하여 인덱스로 범위를 지정하여 더한다.
# reduceat을 풀어쓰면 아래와 같은 코드가 나온다.
print(S)

In [ ]:
# 이 코드는 reduceat을 이해하기 위해 임시로 사용한 코드이다.
array = np.arange(10)
indices = np.array([1,3,4,5])
output = np.add.reduceat(array,indices)  
print(output)

print("Step1 : ", np.add.reduce(array[1:3]))
print("Step2 : ", np.add.reduce(array[3:4]))
print("Step3 : ", np.add.reduce(array[4:5]))
print("Step4 : ", np.add.reduce(array[5:]))

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
# Z에 슬라이스를 사용하여 N에 값을 지정한다. -2와 같은 음수값은 뒤에서 두번째까지 라는 뜻
    birth = (N==3) & (Z[1:-1,1:-1]==0)
# &는 비트연산자다. 때문에 동일한 값만 birth에 들어간다.
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
# |역시 비트연산자다. 때문에 둘 중 하나만 true값일경우 srivove에 값이 들어간다.
    Z[...] = 0
# Z값을 0으로 초기화
    Z[1:-1,1:-1][birth | survive] = 1
# Z의 1번째, 마지막 행 열을 birth survive값이 둘 중 한개 이상이 값이 있을경우 1을 반환한다.
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [ ]:
Z = np.arange(10000)  # 배열 생성
np.random.shuffle(Z)  # Z배열 안의 값의 순서를 랜덤하게 뒤섞는다.
n = 5

# 느린버전
print (Z[np.argsort(Z)[-n:]])
# argsort를 이용하여 오름차순 정렬 뒤 뒤에서 n개를 가져온다.

# 빠른버전
print (Z[np.argpartition(-Z,n)[:n]])
# argpartition은 배열 내 가장 작은 값 n개를 찾은 후 인덱스를 반환한다.

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]  # a에 arrays를 넣고 asarray로 복사한다.
    shape = (len(x) for x in arrays)  # x에 arrays를 넣고 길이를 넣는다.
    
    ix = np.indices(shape, dtype=int) # shape를 indices에 넣어 인덱스 세트를 int데이터 타입으로 반환한다.
    ix = ix.reshape(len(arrays), -1).T  # arrays, -1크기의 배열에 전치연산자를 사용한다.

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]  # ix n열에 arrays n열에 값을 넣는다.  
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)]) # 배열 선언
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
# 배열 목록에서 레코드 배열을 만들어준다.
print(R)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3) # power함수를 사용한 제곱
%timeit x*x*x # 벡터를 3번 곱함
%timeit np.einsum('i,i,i->i',x,x,x) # einsum메소드를 이용한 제곱

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B) # A에 newaxis를 사용해서 차원을 추가한 값을 C에 저장
rows = np.where(C.any((3,1)).all(1))[0]
# any를 통해 3차원 그룹의 각 행들을 비교하여 true가 1개라도 있다면 true를 반환하고 all을 통해 두값이 true인것만 남긴다. where을 통해 인덱스 추출
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1) # E값에 all안의 조건을 둘다 만족하는값을 집어넣는다.
U = Z[~E] # ~는 비트연산자로 E안에 있는값을 제외하고 남은 Z값을 U에 저장한다.
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
# I배열을 열로만들어주고 aragne(8)을 제곱한 값과 동일하다면 true반환 후 False인지 아닌지 비교 후 데이터값을 int형으로 변경
print(B[:,::-1])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
# view를 사용하여 데이터타입을 보여주고, ascontiguousarray를 사용하여 연속배열 반환
_, idx = np.unique(T, return_index=True)  # 언더스코어를 사용하여 값 무시, unique로 고유값 정렬
uZ = Z[idx]
print(uZ)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))       # i->는 sum과 같다.
print(np.einsum('i,i->i', A, B)) # i->i는 A * B와 같다.
print(np.einsum('i,i', A, B))    # i, i는 배열의 내적과 같다.
print(np.einsum('i,j->ij', A, B))    # j->ij는 배열의 외적과 같다.

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1) # pi는 원주율이다.
a = 1
x = a*phi*np.cos(phi) # cos는 코사인이다.
y = a*phi*np.sin(phi) # sin은 사인이다.

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # 선분의 길이

r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # 선분의 길이의 합
r_int = np.linspace(0, r.max(), 200) # 정칙공간
x_int = np.interp(r_int, r, x)       # 통합경로
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1) # np.logical_and.reduce를 사용해서 X의 나머지가 0일때 true인 값들을 합친다.
M &= (X.sum(axis=-1) == n)  # M과 X의행끼리 더한값이 같으면 M에 넣는다.
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size)) # 100 * 1000 크기의 배열 생성
means = X[idx].mean(axis=1) # 배열 X에 인덱스에 idx값을 넣어 평균계산
confint = np.percentile(means, [2.5, 97.5]) # means축을따라 2.5 ,97.5번째 백분위수 계산
print(confint)

[-0.04184574  0.3540292 ]
